### ISSUE TITLE
Update rubygems

### ISSUE THREAD

**Issue by jnylen** [mwpastore/sinja-sequel#2]
Hi @mwpastore,
As Sequel 5 is up now, maybe you should update rubygems?

**Comment by mwpastore** [comment]
I recently merged a PR to do just that, but I needed to do a release. v0.1.7 is now available! Thanks for the nudge.

**Comment by jnylen** [comment]
This somehow fails on running sq:migrate or sq:reset rake tasks (which migrates migrations) on Padrino.
```
/vagrant/vendor/bundle/ruby/2.4.0/gems/sinja-sequel-0.2.0/lib/sinja/sequel.rb:12:in `block in resource'
/vagrant/vendor/bundle/ruby/2.4.0/gems/sinja-sequel-0.2.0/lib/sinja/sequel.rb:12:in `fetch'
/vagrant/vendor/bundle/ruby/2.4.0/gems/sinja-sequel-0.2.0/lib/sinja/sequel.rb:12:in `resource'
```

What it complains about is that the models doesn't exist.

```
  ERROR -  NameError - uninitialized constant Batch:
 /vagrant/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/inflector/methods.rb:269:in `const_get'
rake aborted!
NameError: uninitialized constant Batch
```

Moving back to 1.1.6 works (which also moves Sequel back to 4.49). Also removing sinja-sequel works.

I guess it's because the models doesn't get loaded on migrations and if I require them in the Sinatra app it complains about the tables not existing.

**Comment by mwpastore** [comment]
Sorry to throw another wrench in the works for you. Yes, it does some work on boot now to optimize the class used in the resource block. Ideally, you shouldn't be loading your Sinatra/Padrino apps (or really any application code whatsoever) when you run migrations; it should be a clean environment. Is that a possibility for you?

**Comment by jnylen** [comment]
Hi,
Sadly the way padrino does it is (in Rakefile):
```ruby
PadrinoTasks.use(:database)
PadrinoTasks.use(:sequel)
PadrinoTasks.init
```

Which does seem that it loads some padrino apps.

**Comment by jnylen** [comment]
@mwpastore,
Have you had a check into this?
Otherwise I can revert the commit and use the old one.
